### ISSUE TITLE
Expected values calculated for each chromosome arm

### ISSUE THREAD

**Issue by zhang-jiankun** [open2c/coolpuppy#29]
Hi @Phlya,

Can we use the expected values calculated separately for each chromosome arm as input? Thank you!

Best,
Jiankun

**Comment by Phlya** [comment]
Hi Jiankun,

Sorry - not at the moment, but it will be possible in the future. Working out some compatibility issues with a recent big update of cooltools.
If it's a big factor for you, you can use random shifts, since they are done within a small region they will effectively be only within the same arm.

**Comment by zhang-jiankun** [comment]
Hi Phlya,

Thank you for your kind reply. Look forward to it!!!

Best,
Jiankun
