### ISSUE TITLE
How are zeros dealt with when performing pileups

### ISSUE THREAD

**Issue by gdolsten** [open2c/coolpuppy#41]
Hi Ilya, I wanted to consult your expertise for thinking about how to deal with zeros when performing pileups. One possibility is to average all signal before normalizing with Obs/EXP. The other possibility is to normalize Obs/Exp first, however, then the question becomes what to do with zeros in the Hi-C matrix. Do you ignore them, or add a pseudocount, or a fixed penalty for the presence of a zero?

**Comment by Phlya** [comment]
Why do you think just keeping it as 0 is a problem?

What is tricky are NaNs - they are different from 0, and shouldn't be filled with 0 (and I ended up just counting how many non-NaNs there are in each final pixel, and dividing the final pileup by that instead of just total number of snippets). But I don't remember encountering any problems with zeros.

**Comment by gabedolpten** [comment]
For me, the problem is that if I am calculating Obs/Exp at each location, and then averaging, I cannot take arithmetic mean of the Obs/Exp since this a fold change, I have to take the logarithm first. For example, a fold-change of 2 (log=1) and a fold-change of 1/2  (log=-1) should be considered as a net fold-change of 1 (log=0). If you simply average the fold-changes (2+.5)/2 you get the wrong anser, but if you log-transform first, you get the correct answer (0). Not sure if people have taken this into account in publications previously

This becomes a problem when doing Obs/Exp for individual locations, since many individual Hi-C locations will have a zero, which poses a problem as log(0) is undefined for these matrices, and when you average them it is unclear how to deal with these locations, and it's not clear what values to define for a pseudocount.

Perhaps the solution is to take the average first over all locations and then to normalize by the expected?

**Comment by gabedolpten** [comment]
Now that I think more about it, averaging first over all locations and then dividing by expected would be the exact same as dividing by expected and then averaging. I guess the question is, how is Hi-C data distributed, is it multiplicative or additive? If the baseline is 100, is a change from 100>50 equivalent to a change from 100>150, or is a change from 100>50 equivalent to a change from 100>200?

expected = {100}, data = {50, 150}. --> take arithmetic mean 

expected = {100}, data = {50, 200}. --> log-transform first

**Comment by Phlya** [comment]
You are right, as far as I know this complication is not discussed or even mentioned in the literature. One can simply think of pileups as an average ratio, or as a ratio of averages, depending on the order of operations. In strange cases it can lead to counterintuitive results, as you suggest. However in practice both approaches typically give very similar pileups, so I _think_ it's not an issue with real Hi-C data. I would of course avoid doing average of ratios with super sparse data like single-cell Hi-C, where, afaik, Max Imakaev first originally developed the sum(obs)/sum(expected) approach. But otherwise, so far I haven't observed any significant deviations or unexpected results. Please let me know what you think, and whether you've encountered any strange results because of this with some data.

**Comment by gabedolpten** [comment]
Yes, I haven't seen it discussed either. That's why I brought it up here when I saw you had made this package, because I have seen you make so many great packages & seen your name all over that I figured you would help me think through it. I would think that this would mostly be an issue in data sets where FC may be much greater than 1 in some cases and very close to zero in some cases, since the cases that are very close to zero in the sum(obs)/sum(expected) pileups will have a much lower impact than if you take the log first. 

After some small experimentation I decided to add a pseudocount to my matrices, although I agree that it tends to be quite similar to what you do. 

Let me know if you get any more ideas or think about this more in the future!

**Comment by Phlya** [comment]
How do you add a pseudocount to a matrix of floats, with potentially very small values?

**Comment by gabedolpten** [comment]
Hi Ilya,
I have actually been thinking about this more and I believe that your approach is correct, I am not sure that the Hi-C data needs the LFC. I think this is because the EXPECTED is actually the average of all the data. Therefore, changes in the data themselves affect the expected. For example, if you have just two bins with a total of 200 counts. If bin1 has 150, and bin2 has 50, then the expected is 100. In this case bin1 has 150/100 = 1.5, and bin2 has 50/100 = .5. I think therefore it makes sense to consider changes of "150" and "50" equally "significant", so that they average out to equal 1, and therefore you want to treat them on the O/E scale, not the LOG(O/E) scale

**Comment by Phlya** [comment]
So you think averaging O/E snippets is fine? But not averaging O and dividing by average E? (Both options are available btw)

**Comment by kashyapchhatbar** [comment]
> Why do you think just keeping it as 0 is a problem?
> 
> What is tricky are NaNs - they are different from 0, and shouldn't be filled with 0 (and I ended up just counting how many non-NaNs there are in each final pixel, and dividing the final pileup by that instead of just total number of snippets). But I don't remember encountering any problems with zeros.

Hi @Phlya, Thanks for developing this really cool coolpup.py package. I am a novice when it comes to Hi-C and Micro-C data but based on a "supposedly interesting" pattern for a set of loci, I tried to scour the documentation and ended up here. This conversation seems relevant to me but considering I am a novice, it would be great if I could discuss it with you.

I have a set of ~500 loci and this is how I am generating the pileup plot which gives me an "interesting pattern". 

```python
cool_file = "GSM6281849_RCMC_BR1_merged_allCap_WT_mm39.merged.50.mcool"

resolution = 10000
flank = 500000
# Open cool file with Micro-C data:
clr = cooler.Cooler(f'{cool_file}::/resolutions/{resolution}')

mm39_chromsizes = bioframe.fetch_chromsizes('mm39', provider='ucsc')
mm39_cens = bioframe.fetch_centromeres('mm39', provider='ucsc')
mm39_arms = bioframe.make_chromarms(mm39_chromsizes, mm39_cens)

sites = bioframe.read_table("sites.bed", schema='bed').query(f'chrom in {clr.chromnames}')
expected = expected_cis(clr, ignore_diags=0, view_df=mm39_arms, chunksize=10000)

pup = coolpup.pileup(clr, sites, features_format='bed', view_df=mm39_arms, local=True, expected_df=expected, flank=flank, min_diag=0)

plotpup.plot(pup, score=False, cmap='coolwarm', sym=True, vmin=0.5, vmax=2, height=1.5, plot_ticks=True)
```

![Screenshot from 2023-10-10 05-06-15](https://github.com/open2c/coolpuppy/assets/701627/6d4b835f-0ecf-4a56-b077-d7f81796b639)

Now, this was exciting at first. AND, the coolpuppy log gives me the impression that this pileup is calculated from ALL loci.

```
INFO:coolpuppy:('chr1_q', 'chr1_q'): 39
INFO:coolpuppy:('chr2_q', 'chr2_q'): 36
INFO:coolpuppy:('chr3_q', 'chr3_q'): 36
INFO:coolpuppy:('chr4_q', 'chr4_q'): 22
INFO:coolpuppy:('chr5_q', 'chr5_q'): 26
INFO:coolpuppy:('chr6_q', 'chr6_q'): 24
INFO:coolpuppy:('chr7_q', 'chr7_q'): 22
INFO:coolpuppy:('chr8_q', 'chr8_q'): 19
INFO:coolpuppy:('chr9_q', 'chr9_q'): 16
INFO:coolpuppy:('chr10_q', 'chr10_q'): 25
INFO:coolpuppy:('chr11_q', 'chr11_q'): 13
INFO:coolpuppy:('chr12_q', 'chr12_q'): 15
INFO:coolpuppy:('chr13_q', 'chr13_q'): 25
INFO:coolpuppy:('chr14_q', 'chr14_q'): 24
INFO:coolpuppy:('chr15_q', 'chr15_q'): 15
INFO:coolpuppy:('chr16_q', 'chr16_q'): 21
INFO:coolpuppy:('chr17_q', 'chr17_q'): 14
INFO:coolpuppy:('chr18_q', 'chr18_q'): 19
INFO:coolpuppy:('chr19_q', 'chr19_q'): 13
INFO:coolpuppy:('chrX_q', 'chrX_q'): 20
INFO:coolpuppy:Total number of piled up windows: 444
```

I scoured the Hi-C and TAD literature to see what this pattern was about and after browsing few papers and patterns, I suspect the pattern is from loci which are close to centromeres and obviously looks like they are within domains. So, I decided to subsample these sites and see if the pattern still exists.

```python
pup = coolpup.pileup(clr, sites.sample(len(sites)//2), features_format='bed', view_df=mm39_arms, local=True, expected_df=expected, flank=flank, min_diag=0)

plotpup.plot(pup, score=False, cmap='coolwarm', sym=True, vmin=0.5, vmax=2, height=1.5, plot_ticks=True)
```

And, not to my surprise, the pattern disappeared.

![Screenshot from 2023-10-10 05-15-29](https://github.com/open2c/coolpuppy/assets/701627/61e29661-df66-408f-b928-7d602a0e7c60)

```
INFO:coolpuppy:('chr1_q', 'chr1_q'): 22
INFO:coolpuppy:('chr2_q', 'chr2_q'): 19
INFO:coolpuppy:('chr3_q', 'chr3_q'): 23
INFO:coolpuppy:('chr4_q', 'chr4_q'): 11
INFO:coolpuppy:('chr5_q', 'chr5_q'): 12
INFO:coolpuppy:('chr6_q', 'chr6_q'): 12
INFO:coolpuppy:('chr7_q', 'chr7_q'): 11
INFO:coolpuppy:('chr8_q', 'chr8_q'): 12
INFO:coolpuppy:('chr9_q', 'chr9_q'): 8
INFO:coolpuppy:('chr10_q', 'chr10_q'): 12
INFO:coolpuppy:('chr11_q', 'chr11_q'): 3
INFO:coolpuppy:('chr12_q', 'chr12_q'): 9
INFO:coolpuppy:('chr13_q', 'chr13_q'): 10
INFO:coolpuppy:('chr14_q', 'chr14_q'): 9
INFO:coolpuppy:('chr15_q', 'chr15_q'): 7
INFO:coolpuppy:('chr16_q', 'chr16_q'): 7
INFO:coolpuppy:('chr17_q', 'chr17_q'): 7
INFO:coolpuppy:('chr18_q', 'chr18_q'): 9
INFO:coolpuppy:('chr19_q', 'chr19_q'): 8
INFO:coolpuppy:('chrX_q', 'chrX_q'): 11
INFO:coolpuppy:Total number of piled up windows: 222
```


But, then it reappeared again in another subset and disappeared in another subset. After playing best of 5, I saw the pattern 3/5 times. Then I decided to subsample it further and its score stood at 2/10 times.

```python
pup = coolpup.pileup(clr, sites.sample(len(sites)//4), features_format='bed', view_df=mm39_arms, local=True, expected_df=expected, flank=flank, min_diag=0)

plotpup.plot(pup, score=False, cmap='coolwarm', sym=True, vmin=0.5, vmax=2, height=1.5, plot_ticks=True)
```

```
INFO:coolpuppy:('chr1_q', 'chr1_q'): 4
INFO:coolpuppy:('chr2_q', 'chr2_q'): 8
INFO:coolpuppy:('chr3_q', 'chr3_q'): 6
INFO:coolpuppy:('chr4_q', 'chr4_q'): 5
INFO:coolpuppy:('chr5_q', 'chr5_q'): 9
INFO:coolpuppy:('chr6_q', 'chr6_q'): 9
INFO:coolpuppy:('chr7_q', 'chr7_q'): 3
INFO:coolpuppy:('chr8_q', 'chr8_q'): 3
INFO:coolpuppy:('chr9_q', 'chr9_q'): 6
INFO:coolpuppy:('chr10_q', 'chr10_q'): 9
INFO:coolpuppy:('chr11_q', 'chr11_q'): 4
INFO:coolpuppy:('chr12_q', 'chr12_q'): 8
INFO:coolpuppy:('chr13_q', 'chr13_q'): 5
INFO:coolpuppy:('chr14_q', 'chr14_q'): 7
INFO:coolpuppy:('chr15_q', 'chr15_q'): 5
INFO:coolpuppy:('chr16_q', 'chr16_q'): 9
INFO:coolpuppy:('chr17_q', 'chr17_q'): 3
INFO:coolpuppy:('chr18_q', 'chr18_q'): 5
INFO:coolpuppy:('chrX_q', 'chrX_q'): 3
INFO:coolpuppy:Total number of piled up windows: 111
```

I guess you know what I am trying to get at. Along with the Total number of piled up windows, can you add in the log, total number of piled up windows (with non-NaN values) too? This will certainly help people to not get excited prematurely. Is there an argument which allows me to do this?

Thanks again for a really cool package and inadvertently helping me to dive in this field.

**Comment by kashyapchhatbar** [comment]
The `numpy` arrays stored in `num` and `data` are shaped according to the heatmap

```python
pup["num"].values[0].shape, pup["data"].values[0].shape
```

```
((101, 101), (101, 101))
```

The `num` has either 0 (lower diagonal and places before centromere) or 1 (upper diagonal where there is some signal) while the `data` has the values that are plotted.

Is there a way to get some sort of counts for every pixel which shows the number of loci contributed to the profile? If a really prominent pattern is there at ~250kb, then this other count matrix could help me validate that it is either coming from a handful of loci or majority of loci.

Hope it makes sense, thanks for your quick reply.

**Comment by Phlya** [comment]
>The num has either 0 (lower diagonal and places before centromere) or 1 (upper diagonal where there is some signal) while the data has the values that are plotted.

The the highest value you get in `num` is 1, it means there is only one region contributing to the pileup.

>Is there a way to get some sort of counts for every pixel which shows the number of loci contributed to the profile? If a really prominent pattern is there at ~250kb, then this other count matrix could help me validate that it is either coming from a handful of loci or majority of loci.

This is exactly what the `num` matrix shows - the number of non-NaN pixels contributing to the corresponding pixel in `data`.
