### ISSUE TITLE
updated cooltools makes coolpup.py to fail

### ISSUE THREAD

**Issue by NoeliaDiaz** [open2c/coolpuppy#47]
Hi there,
I tried to run coolpup.py version 0.9.5 like this:

```coolpup.py my_hic_data.cool my_domains.bed --rescale --local```

and I got the following error regarding cooltools/snipping:

``` Traceback (most recent call last):
  File "~/.local/bin/coolpup.py", line 5, in <module>
    from coolpuppy.__main__ import main
  File "~/.local/lib/python3.8/site-packages/coolpuppy/__init__.py", line 1, in <module>
    from .coolpup import *
  File "~/.local/lib/python3.8/site-packages/coolpuppy/coolpup.py", line 14, in <module>
    from cooltools import numutils, snipping
ImportError: cannot import name 'snipping' from 'cooltools' (~/.local/lib/python3.8/site-packages/cooltools/__init__.py)
```

A colleague spotted an update in cooltools code (coolpup.py runs fine for me with an older version of cooltools 0.4.1) where they have renamed the file:

 ```cooltools/snipping.py``` into ```cooltools/api/snipping.py```  

and other calls 

```cooltools.snipping``` with ```cooltools.api.snipping ```...

so when cooltools tries to import snipping, snipping is not found and coolpup.py fails to run.

Cheers!

**Comment by Phlya** [comment]
Thanks Noelia! I am aware and started working on it already 👍

**Comment by Phlya** [comment]
Hi Noelia,

I just made the changes that should fix any problems with new cooltools. There are some changes you have to be aware of: format of expected changed slightly in cooltools, and old files won't work anymore. You can either recalculate them, or simply modify old files to have two region columns (`region1` and `region2`). This is because inter-region expected can now be written in the same file.

Also cooltools now has a `pileup` command. It's limited compared to coolpuppy, so they will both coexist for now at least. However I wanted to align their interfaces as much as possible, so I modified the API in coolpuppy: renamed some arguments and changed the behaviour a little. I described the changes in the comment here: https://github.com/open2c/coolpuppy/pull/48

Hope this helps and the changes aren't too annoying! I hope to release all this soon, since the released version of coolpuppy is very outdated at this point,

**Comment by Phlya** [comment]
Let me know if anything is unclear, closing this issue now.
