### ISSUE TITLE
coolpup.py Pile-ups of predefined regions pairs,

### ISSUE THREAD

**Issue by mb6434** [open2c/coolpuppy#67]
Dear Efriman,

I am using your tool in order to assess interaction between two datasets. I thus constructed a bedpe file with predefined regions pairs. I am thus wondering that what is plotted on the X and Y axis in the plot. 
So I have a bedpe file as an exemple:
(dataset1)chr start end (dataset2) chr start end.

Does the dataset 1 correspond to the X axis and dataset2 to the Y axis, or is it the reverse?

Please, find attached a file in which I put informations in a way that I hope you will understand my point.

Thank you very much for your help,

Best regards,

Mathilde
[pileup_regionpaired_question.pdf](https://github.com/open2c/coolpuppy/files/8670852/pileup_regionpaired_question.pdf)

**Comment by Phlya** [comment]
Dear Mathilde,

dataset1 will be on Y, and 2 will be on X. However beware of cases when coordinates of dataset1 are bigger than coordinates of dataset2 when you are merging them, (I think) those cases will be just ignored by the software since they map to the bottom half of the cooler which is normally empty.

**Comment by mb6434** [comment]
Thank you very much for your clear and fast answer. I think, I got what your point. If I well understood this mean that only one side of the diagonal is taken into account. Thus, I should construct another bedpe file by inverting the position of datatset 1 and 2, in order to look at the region paired previously ignored.

If it is not clear, I could make a draw!

Thank you very much,

Mathilde

**Comment by Phlya** [comment]
So, I finally gave it a try to be sure. So, the regions on the lower diagonal are not ignored, but since in a typical cooler the bottom half is empty, it's still important to ensure the left side of your region has smaller coordinates than the right, otherwise this is what it'll produce:
![below](https://user-images.githubusercontent.com/2895034/172610514-b11649b0-89ac-4206-94f3-a3f73c847517.png)

And when the region is in the upper diagonal, it looks like this:
![above](https://user-images.githubusercontent.com/2895034/172610640-47506c74-f10d-4af0-91c2-986689911a66.png)

**Comment by mb6434** [comment]
Thank you very much Phlya and sorry to not thank you before. I am new in github. I just saw your answer.

**Comment by HengkuanLi** [comment]
Hello, my BEDPE file does not have any cases where dataset1 is greater than dataset2, so why do I still see missing data in the lower-left corner? Thank you very much for your help.

**Comment by Phlya** [comment]
Probably the regions you are averaging are quite close to the diagonal. The area below the main diagonal, and by default the first two diagonals of the upper half of the heat map, are masked, so sometimes the bottom corner of the pileup is empty if all of the pixels contributing to it are from the masked area
